model:
  name_model: "model_sweep10_aspretrained"
  dir_save_results: "./model_sweep10_aspretrained/"
  new_model: True
  use_pretrained_model: True
  path_to_saved_model_gen: "./sweep_10/models/sweep_10_gen_best.pt"
  path_to_saved_model_disc: "./sweep_10/models/sweep_10_disc_best.pt"

data:
  processed_data_folder: "/mnt/shared/divided_data/"
  dataset: "lungCTData"
  start_point_validation_data: 0
  end_point_validation_data: 800


training:
  batch_size_train: 15
  batch_size_validation: 8
  n_epochs: 50
  steps_to_complete_bfr_upd_disc: 4
  steps_to_complete_bfr_upd_gen: 2
  transformations: 
    transform: "AddGaussianNoise"
    info:
      lung_area: False
      intensity: 0.3157719473254114
      mean: 0.7469069764183585
      std: 0.17845815118827982

loss: 
  criterion: 
    name: "BCELoss"
  regularizer:
    type:
      - "MSE"
    regularization:
      - 8
  
optimizer:
  type: "Adam"
  lr: 0.0002
  info:
    betas: [0.4597517629105646, 0.999]
  path_to_saved_gen_optimizer: ""
  path_to_saved_disc_optimizer: ""

lr_scheduler:
  activate: True
  scheduler_type: "LinearLR"
  epoch_to_switch_to_lr_scheduler: 10
  info:
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 5
  path_to_saved_gen_scheduler: ""
  path_to_saved_disc_scheduler: ""

save_models_and_results:
  step_to_safe_save_models: 4
  save_best_model: True

wandb:
  activate: True