model:
  name_model: "model_test"
  dir__trained_model: "./model_test/"
  use_best_version: True

data:
  processed_data_folder: "/mnt/shared/divided_data/"
  dataset: "lungCTData"
  batch_size: 10
  transformations: 
    transform: "AddGaussianNoise"
    info:
      lung_area: False
      intensity: 0.3157719473254114
      mean: 0.7469069764183585
      std: 0.17845815118827982

evaluation:
  bQualitativa: True
  bFID: True
  bSSIM: True
  bDice: False