model:
  name_model: "model_sweep412_aspretrained_lungmask"
  dir_save_results: "./model_sweep412_aspretrained_lungmask/"
  new_model: True
  use_pretrained_model: True
  path_to_saved_model_gen: "./model_sweep412_aspretrained/models/model_sweep412_aspretrained_gen_trained.pt"
  path_to_saved_model_disc: "./model_sweep412_aspretrained/models/model_sweep412_aspretrained_disc_trained.pt"

data:
  processed_data_folder: "/mnt/shared/labelmaskdata/"
  dataset: "lungCTData"
  start_point_validation_data: 0
  end_point_validation_data: 800


training:
  batch_size_train: 15
  batch_size_validation: 8
  n_epochs: 50
  steps_to_complete_bfr_upd_disc: 1
  steps_to_complete_bfr_upd_gen: 1
  transformations: 
    transform: "AddGaussianNoise"
    info:
      lung_area: False
      intensity: 0.7572552489767528
      mean: 0.525049557342425
      std: 0.4755411392298655

loss: 
  criterion: 
    name: "MSELoss"
  regularizer:
    type:
      - "MAE"
    regularization:
      - 4
  
optimizer:
  type: "Adam"
  lr: 0.0002
  info:
    betas: [0.8811316699367162, 0.999]
  path_to_saved_gen_optimizer: ""
  path_to_saved_disc_optimizer: ""

lr_scheduler:
  activate: True
  scheduler_type: "LinearLR"
  epoch_to_switch_to_lr_scheduler: 10
  info:
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 5
  path_to_saved_gen_scheduler: ""
  path_to_saved_disc_scheduler: ""

save_models_and_results:
  step_to_safe_save_models: 4
  save_best_model: True

wandb:
  activate: True