model:
  name_model: "sweep_segm_125"
  use_best_version: False

data:
  processed_data_folder: "C:/Users/julia/OneDrive/Dados_escolinha/data_unet/"
  dataset: "processedCTData"
  batch_size: 10
  transformations:

evaluation:
  bQualitativa: False
  bFID: False
  bSSIM: False
  bDice: True