model:
  name_model: "gen_dice_loss_freeze_early_stopping"
  dir_save_results: "./gen_dice_loss_freeze_early_stopping/"
  new_model: True
  path_to_saved_model: "./gen_dice_loss_freeze_early_stopping/models/gen_dice_loss_freeze_early_stopping_best.pt"
  fine_tunning: True
  freeze_layers: True
  trained_gen_path: "C:/Users/julia/OneDrive/Dados_escolinha/sweep_10_gen_best.pt"


data:
  processed_data_folder: "C:/Users/julia/OneDrive/Dados_escolinha/data_unet/"
  dataset: "processedCTData"
  start_point_train_data: 0
  end_point_train_data: 100
  start_point_validation_data: 0
  end_point_validation_data: 10

training:
  batch_size_train: 20
  batch_size_validation: 8
  n_epochs: 50
  early_stopping : True
  patience : 5
  delta : 0.01

loss: 
  criterion: 
    name: "DiceLoss"
  
optimizer:
  type: "Adam"
  lr: 0.0002
  info:
    betas: [0.5, 0.999]
  path_to_saved_optimizer: ""

save_models_and_results:
  step_to_safe_save_models: 3
  save_best_model: True