model:
  name_model: "model_test_unet"
  dir_save_results: "./model_test_unet/"
  new_model: True
  fine_tunning: False
  freeze_layers: False
  path_to_saved_model: ""
  

data:
  processed_data_folder: "/mnt/shared/divided_data/"
  dataset: "processedCTData"
  start_point_train_data: 0
  end_point_train_data: 10
  start_point_validation_data: 0
  end_point_validation_data: 8


training:
  batch_size_train: 20
  batch_size_validation: 8
  n_epochs: 6
  early_stopping : True
  patience : 5
  delta : 0.01

loss: 
  criterion: 
    name: "DiceLoss"
  
optimizer:
  type: "Adam"
  lr: 0.0002
  info:
    betas: [0.5, 0.999]
  path_to_saved_optimizer: ""

save_models_and_results:
  step_to_safe_save_models: 3
  save_best_model: True