model:
  name_model: "model_article_complete"
  dir_save_results: "./model_article_complete/"
  new_model: True
  path_to_saved_model_gen: ""
  path_to_saved_model_disc: ""

data:
  processed_data_folder: "/mnt/shared/divided_data/"
  dataset: "lungCTData"


training:
  batch_size_train: 20
  batch_size_validation: 8
  n_epochs: 200
  steps_to_complete_bfr_upd_disc: 1
  steps_to_complete_bfr_upd_gen: 1
  transformations: 
    transform: "AddUniformNoise"
    info:
      lung_area: False
      intensity: 1

loss: 
  criterion: 
    name: "BCEWithLogitsLoss"
  regularizer:
    type:
      - "MAE"
    regularization:
      - 10
  
optimizer:
  type: "Adam"
  lr: 0.0002
  info:
    betas: [0.5, 0.999]
  path_to_saved_gen_optimizer: ""
  path_to_saved_disc_optimizer: ""

lr_scheduler:
  activate: True
  scheduler_type: "LinearLR"
  epoch_to_switch_to_lr_scheduler: 100
  info:
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 5
  path_to_saved_gen_scheduler: ""
  path_to_saved_disc_scheduler: ""

save_models_and_results:
  step_to_safe_save_models: 10
  save_best_model: True

wandb:
  activate: True