model:
  name_model: "unet_example"
  dir_save_results: "./unet_example/"
  new_model: True
  path_to_saved_model: "./unet_example/models/unet_example_best.pt"


data:
  processed_data_folder: "C:/Users/julia/OneDrive/Dados_escolinha/data_unet/"
  train_dataset: "seg_train"
  val_dataset: "seg_val"
  start_point_train_data: 0
  end_point_train_data: 14000
  start_point_validation_data: 0
  end_point_validation_data: 2000

training:
  batch_size_train: 20
  batch_size_validation: 8
  n_epochs: 50

loss: 
  criterion: 
    name: "BCEWithLogitsLoss"
  
optimizer:
  type: "Adam"
  lr: 0.0002
  info:
    betas: [0.5, 0.999]
  path_to_saved_optimizer: ""

save_models_and_results:
  step_to_safe_save_models: 3
  save_best_model: True