model:
  name_model: "gen_sweep412"
  dir_save_results: "./gen_sweep412/"
  new_model: True
  fine_tunning: True
  freeze_layers: True
  trained_gen_path: "/home/leticia/Documentos/PulmoNet/model_sweep412_aspretrained/models/model_sweep412_aspretrained_gen_trained.pt"


data:
  processed_data_folder: "/mnt/shared/divided_data/"
  train_dataset: "seg_train"
  val_dataset: "seg_val"
  start_point_train_data: 0
  end_point_train_data: 4600
  start_point_validation_data: 0
  end_point_validation_data: 2000


training:
  batch_size_train: 20
  batch_size_validation: 8
  n_epochs: 30

loss: 
  criterion: 
    name: "DiceLoss"
  
optimizer:
  type: "Adam"
  lr: 0.0002
  info:
    betas: [0.5, 0.999]
  path_to_saved_optimizer: ""

save_models_and_results:
  step_to_safe_save_models: 3
  save_best_model: True