model:
  name_model: "sweep_64"
  use_best_version: True

data:
  processed_data_folder: "/mnt/shared/divided_data"
  dataset: "lungCTData"
  batch_size: 10
  transformations: 
    transform: "AddGaussianNoise"
    info:
      lung_area: True
      intensity: 0.8185145299699786
      mean: 0.5597838196435154
      std: 0.2229110594696566

evaluation:
  bQualitativa: True
  bFID: True
  bSSIM: True